var gameRules = [
    { name:'Universal RPGs', desc:'[Coming Soon]', entry:'Game Rule (General)' },
    { name:'GMs and Players', desc:'[Coming Soon]', entry:'Game Rule (General)' },
    { name:'Who Decides? Resolving Disputes', desc:'[Coming Soon]', entry:'Game Rule (General)' },
    { name:'Time to Die! What is with these dice?', desc:'[Coming Soon]', entry:'Game Rule (General)' },
    { name:'Session Zero', desc:'[Coming Soon]', entry:'Game Rule (General)' },
    { name:'UGRPG', desc:'[Coming Soon]', entry:'Game Rule (General)' },
    { name:'ICRPG and D&D', desc:'[Coming Soon]', entry:'Game Rule (General)' },
    { name:'Mythic GM', desc:'[Coming Soon]', entry:'Game Rule (General)' },
    { name:'Building a Character', desc:'[Coming Soon]', entry:'Game Rule (Character)' },
    { name:'Starting Character Math', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Base Stats and Effort', desc:'[Coming Soon]', entry:'Game Rule (Character)' },
    { name:'Attempts and Contests', desc:'[Coming Soon]', entry:'Game Rule (Character)' },
    { name:'Alternative Attempt Methods', desc:'[Coming Soon]', entry:'Game Rule (Character)' },
    { name:'Playable Kinds', desc:'[Coming Soon]', entry:'Game Rule (Character)' },
    { name:'Alignment, Ethos, Reputation and Piety', desc:'[Coming Soon]', entry:'Game Rule (Character)' },
    { name:'Earning XP and SP', desc:'[Coming Soon]', entry:'Game Rule (Character)' },
    { name:'Milestones and Leveling', desc:'[Coming Soon]', entry:'Game Rule (Character)' },
    { name:'Hearts and HP', desc:'[Coming Soon]', entry:'Game Rule (Character)' },
    { name:'Target Numbers and Defense', desc:'[Coming Soon]', entry:'Game Rule (Character)' },

    { name:'Recovery and Death', desc:'[Coming Soon]', entry:'Game Rule (Character)' },
    { name:'Aptitude, Zeal, Grit, Bits, Mana, and Ethos', desc:'[Coming Soon]', entry:'Game Rule (Character)' },
    { name:'Paying the Cost, Easy, Hard, and Advantage', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Spell Disciplines', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Spell Mastery and Pips', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Spell Casting', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Spell Casting Mechanics', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Spell Casting Extended Mechanics', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Sidekicks, Hirelings and Adoration', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Difficult Terrain', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Being Prone', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Falling', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'About Languages', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Unlisted Stats', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Effort Damage Terms', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Subclass Signature Abilities', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Strength Proficiency', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Dexterity Proficiency', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Constitution Proficiency', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Intelligence Proficiency', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Wisdom Proficiency', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Charisma Proficiency', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Focus', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Size Values', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Armor Values', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Madness', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Tattoo Attunement', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Ship Repair', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'War Machine Mishaps', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Cosmology', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Celestial Choir', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Demonology', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Lothic Daemonology', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Deviltry', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Closed Domain', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Wandering the Mists', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Chain Lightning Game', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Deck Rules', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Deck Rules: Tarokka', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Tarokka Reading: Strahd', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Weapon Rules: Ammunition', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Weapon Rules: Finesse/Versatile', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Weapon Rules: Heavy/Light', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Weapon Rules: Loading', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Weapon Rules: Two-Handed', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Weapon Rules: Range', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Tool Rules: Complex Tasks', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Ruidium Corruption', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Severe Diseases', desc:'[Coming Soon]', entry:'Game Rule' },
    { name:'Arcanum', desc:'[Coming Soon]', entry:'Game Rule' }
];